import DataManager as dm
from sklearn.ensemble import RandomForestClassifier


""" get the RandomForest classifier (generated by TPOT) """
def get_classifier():		

	clf = RandomForestClassifier(class_weight="balanced_subsample", criterion="entropy", 
		max_depth=7, max_leaf_nodes=8, min_impurity_decrease=0.0, min_samples_leaf=8, 
		min_samples_split=3, min_weight_fraction_leaf=0.0, n_estimators=500)	

	return clf


""" run the RandomForest classifier """
def run_RandomForest(samples=50000):
	"""
	N_way:	number of different classes for the N-Way one-shot-learning
	n_chars:number of different characters to be used for learning

	return:	classifier
	"""

	clf = get_classifier()
	X_train, y_train, X_test, y_test = dm.train_test_set_generator(samples=samples)
	
	clf.fit(X_train, y_train)
	print("Random Forest Classifier score: %f" % clf.score(X_test, y_test))

	return clf